### ISSUE TITLE
Update shorts single serve section

### ISSUE THREAD

**Issue by sean-rad-dude** [lokioatmeal/dev-dukes#3]
We need to find a way to say that they have 8 ct and 12 ct  packs on the product overview page.

try this:

ORIGINAL RECIPE

SMOKED
SHORTY® SAUSAGES

8 CT / 12 CT AVAILABLE

$15.49
LEARN MORE

**Comment by lokioatmeal** [comment]
Please see this URL to see this request implemented.

[https://dev-dukes.myshopify.com/?preview_theme_id=152442118](https://dev-dukes.myshopify.com/?preview_theme_id=152442118)

**Comment by lokioatmeal** [comment]
This is no longer needed since they are removing the variants.
