### ISSUE TITLE
Make pattern and footer images 30 percent smaller

### ISSUE THREAD

**Issue by sean-rad-dude** [lokioatmeal/dev-dukes#4]
Client would like to make the footer color bar, pattern and image 30% smaller.

**Comment by lokioatmeal** [comment]
This will require new files for all of those footer illustrations that are cropped and masked to accept the height of the new pattern bar. Assuming this request also means that the pattern bar is supposed to be shorter.

**Comment by lokioatmeal** [comment]
Please see the URL here.

[dukesmeats.com/?preview_theme_id=152480582](http://dukesmeats.com/?preview_theme_id=152480582)
