### ISSUE TITLE
Change ADD TO CART BUTTON ?

### ISSUE THREAD

**Issue by sean-rad-dude** [lokioatmeal/dev-dukes#5]
Can we change the ADD TO CART button to be the style of the other button on the site only with the colors we have for the product buttons now. IE red, orange, green etc?

Not sure if this will work?

**Comment by lokioatmeal** [comment]
Please see this dev theme for this request below. Note that this theme only changes the button and does not actually have the cart feature turned on. Meaning, while the buttons are there for visual review, they do not work.

[https://dev-dukes.myshopify.com/?preview_theme_id=152440518](https://dev-dukes.myshopify.com/?preview_theme_id=152440518)
