### ISSUE TITLE
Duke's Legal/Ops Updates

### ISSUE THREAD

**Issue by SydSurratt** [lokioatmeal/dev-dukes#6]
HOMEPAGE - SUGAR SECTION AT THE BOTTOM:
“At Dukes we don’t believe in sugarcoating the truth or our meats?”
 Change to:
“At Dukes we don’t believe in sugarcoating the truth.”
“Learn Why we Think Putting Sugar in our Meats is Nuts” – BUTTON
Change to “Learn Why We Don’t Add Extra Sugar in Our Meats”
Sugar paragraph...
Remove “Sugar as a “fast tenderizer”

REAL, WHOLE INGREDIENTS PAGE: 
First paragraph under the top banner:
Take out “fresh” before meats in the paragraph that reads “When you season and marinate fresh meats...etc”
 
Hatch paragraph:
Add “only” in front of “dried spices.” so it will read: “...that can’t be faked with only dried spices.” (At the very end of the paragraph)
 
Chorizo paragraph:
Please update to “15lbs of fresh cilantro”
Drop the last sentence: “That’s right… we said…”
 
Chipotle paragraph:
HEADLINE: Change “Serrano” to “Crushed Chipotle” Peppers
Reword copy to: “We [then] use them to create a tasty barbeque marinade for these one-of-a-kind 100%…..”
 

PROCESS:
 
No. 1
Add roughly to: “….delivered to our kitchen at roughly 32 degrees…” (and remove “wherever possible.”)
 
No. 2
Drop “Fresh” off headline and change to: “Real, Whole Ingredients…”
 

CONTACT:
ADD TEXT THAT SAYS: “Please include the flavor of the product you are inquiring about as well as the best by date and the numbers and letters near the best by date.”

**Comment by lokioatmeal** [comment]
I pushed this list of requests through to the live website.

**Comment by lokioatmeal** [comment]
Please close this task if you are satisfied.
